services:
  - type: web
    name: shuttershuttle
    env: python
    plan: free
    buildCommand: ./render_build.sh
    startCommand: gunicorn server:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: 1
      - key: CMAKE_ARGS
        value: "-DDLIB_USE_CUDA=0 -DDLIB_NO_GUI_SUPPORT=1"
    autoDeploy: true

  - type: pserv
    name: shuttershuttle-db
    dbName: shuttershuttle
    plan: free